#+TITLE: UE Apprentissage SIA S9

* How to get the course

In order to download all the material, just do in the terminal:
#+begin_src sh
git clone https://src.koda.cnrs.fr/mathieu.fauvel.4/n7_iati.git
#+end_src

then enter in the repository
#+begin_src sh
cd n7_iati
#+end_src

If you run the following command you should get something like
#+begin_src sh :results code :exports all
tree -L 1
#+end_src

#+begin_src sh
.
├── auto
├── Course
├── Data
├── environment.yml
├── Examen
├── Notebooks
├── README.org
├── README.org~
└── TP_Perso

7 directories, 3 files
#+end_src

The repertory =Course= contains the pdf used during the session and =Notebooks= contains the associated jupyter notebooks.

To update the repository
#+begin_src sh
git pull origin main
#+end_src

* Course organization
| Days                | Start | End   | Name                                      | Room      |
|---------------------+-------+-------+-------------------------------------------+-----------|
| Lundi 21/09/2026    | 14h00 | 15h45 | N9EE41C - CM - Apprentissage supervisé    | C304 (32) |
| Lundi 21/09/2026    | 16h15 | 18h00 | N9EE41C - CM - Apprentissage supervisé    | C304 (32) |
|---------------------+-------+-------+-------------------------------------------+-----------|
| Mercredi 30/09/2026 | 14h00 | 15h45 | N9EE41C - CM - Apprentissage supervisé    | C302 (18) |
| Mercredi 30/09/2026 | 16h15 | 18h00 | N9EE41C - CM - Apprentissage supervisé    | C302 (18) |
|---------------------+-------+-------+-------------------------------------------+-----------|
| Lundi 05/10/2026    | 14h00 | 15h45 | N9EE41C - CM - Apprentissage supervisé    | C206 (32) |
| Lundi 05/10/2026    | 16h15 | 18h00 | N9EE41C - CM - Apprentissage supervisé    | C206 (32) |
|---------------------+-------+-------+-------------------------------------------+-----------|
| Lundi 12/10/2026    | 14h00 | 15h45 | N9EE41C - PERSO - Apprentissage supervisé | C306 (32) |
|---------------------+-------+-------+-------------------------------------------+-----------|
| Mercredi 14/10/2026 | 08h00 | 09h45 | N9EE41C - TP - Apprentissage supervisé    | C301(18)  |
| Mercredi 14/10/2026 | 10h15 | 12h00 | N9EE41C - TP - Apprentissage supervisé    | C301(18)  |
|---------------------+-------+-------+-------------------------------------------+-----------|
| Lundi 19/10/2026    | 10h15 | 12h00 | N9EE41C - PERSO - Apprentissage supervisé | C306 (32) |
|---------------------+-------+-------+-------------------------------------------+-----------|
| Mercredi 21/10/2026 | 10h15 | 12h00 | N9EE41C - PERSO - Apprentissage supervisé | C304 (32) |
|---------------------+-------+-------+-------------------------------------------+-----------|
| Mardi 17/11/2026    | 10h15 | 12h00 | N9EE41C - PERSO - Apprentissage supervisé | C302 (18) |
| Mardi 17/11/2026    | 16h15 | 18h00 | N9EE41C - TP - Apprentissage supervisé    | C302 (18) |
|---------------------+-------+-------+-------------------------------------------+-----------|
| Lundi 23/11/2026    | 10h15 | 11h45 | N9EE41C - EXAM - Apprentissage supervisé  | C304 (32) |

The evaluation will be
- Home Labwork: 40%, by pair.
- Exam: 60%, individual (notes and course materials allowed).
  
* Python Environment
You can recover the environment used for the labworks with (for conda users):
#+begin_src sh
# replace my-env by the name you want
conda env create --name my-env --file environment.yml
#+end_src

The =environment.yml= file is here: [[file:./environment.yml][environment.yml]]

* Web service
It is possible to create an account and work with GPU here: https://datalab.sspcloud.fr/

** Configuration
Nothing to do, just authenticate yourself.
. 
** Use
First launch an instance =Jupyter-pytorch-gpu= with default parameters. Once connected to the instance, clone the repository in a shell from the jupyter-lab environment.

#+begin_src sh
git clone https://src.koda.cnrs.fr/mathieu.fauvel.4/n7_iati.git
#+end_src

I suggest to add another remote repository to save your work between session, as all the local data of the instance will be removed/deleted after some days (currently 7). Suppose you have an account on gitlab.com, you can create an empty repository named "n7_iati" and commit your work there.

#+begin_src sh
git remote add origin https://gitlab.com/mfauvel/n7_iati.git
#+end_src

Now you can pull the last version of the course as

#+begin_src sh
git pull origin main
#+end_src

you can also push your modification to your account as
#+begin_src sh
git push gitlab main
#+end_src

Also, between session, if the instance was deleted, you just need to clone your repository to recover you environment.
